package portal.vomanager.domain;

// Generated 23-gen-2012 12.27.05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vo generated by hbm2java
 */
@Entity
@Table(name = "VO", catalog = "PortalUser")
public class Vo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7141843908911661031L;
	private int idVo;
	private String vo;
	private String host;
	private String description;
	private String voManagerMail;
	private String enrollementUrl;
	private String discipline;
	private String middleware;
	private Date insertTime;
	private String aup;
	private String configured;

	public Vo() {
	}

	public Vo(String vo, String host, String description, String discipline,
			String middleware, Date insertTime, String aup, String configured) {
		this.vo = vo;
		this.host = host;
		this.description = description;
		this.discipline = discipline;
		this.middleware = middleware;
		this.insertTime = insertTime;
		this.aup = aup;
		this.configured = configured;
	}

	public Vo(String vo, String host, String description, String voManagerMail,
			String enrollementUrl, String discipline, String middleware,
			Date insertTime, String aup, String configured) {
		this.vo = vo;
		this.host = host;
		this.description = description;
		this.voManagerMail = voManagerMail;
		this.enrollementUrl = enrollementUrl;
		this.discipline = discipline;
		this.middleware = middleware;
		this.insertTime = insertTime;
		this.aup = aup;
		this.configured = configured;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVO", unique = true, nullable = false)
	public int getIdVo() {
		return this.idVo;
	}

	public void setIdVo(int idVo) {
		this.idVo = idVo;
	}

	@Column(name = "VO", nullable = false, length = 100)
	public String getVo() {
		return this.vo;
	}

	public void setVo(String vo) {
		this.vo = vo;
	}

	@Column(name = "Host", nullable = false, length = 100)
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "Description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "VoManagerMail", length = 100)
	public String getVoManagerMail() {
		return this.voManagerMail;
	}

	public void setVoManagerMail(String voManagerMail) {
		this.voManagerMail = voManagerMail;
	}

	@Column(name = "EnrollementURL", length = 100)
	public String getEnrollementUrl() {
		return this.enrollementUrl;
	}

	public void setEnrollementUrl(String enrollementUrl) {
		this.enrollementUrl = enrollementUrl;
	}

	@Column(name = "Discipline", nullable = false, length = 100)
	public String getDiscipline() {
		return this.discipline;
	}

	public void setDiscipline(String discipline) {
		this.discipline = discipline;
	}

	@Column(name = "Middleware", nullable = false, length = 7)
	public String getMiddleware() {
		return this.middleware;
	}

	public void setMiddleware(String middleware) {
		this.middleware = middleware;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Insert_Time", nullable = false, length = 19)
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "AUP", nullable = false, length = 65535)
	public String getAup() {
		return this.aup;
	}

	public void setAup(String aup) {
		this.aup = aup;
	}
	
	@Column(name = "configured", nullable = false, length = 6)
	public String getConfigured() {
		return this.configured;
	}

	public void setConfigured(String configured) {
		this.configured = configured;
	}

}
